__default__:
  time: 120 # Default time (minutes). A time limit of zero requests that no time limit be imposed
  mem: 10G # Default memory. A memory size specification of zero grants the job access to all of the memory on each node.
  cpus-per-task: 1
  nodes: 1
  ntasks: 1

trim_reads_se:
  mem: 5G
  cpus-per-task: 4

trim_reads_pe:
  mem: 5G
  cpus-per-task: 4

map_reads:
  cpus-per-task: 12

call_variants:
  time: 1-0
  cpus-per-task: 8
